version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example@123
      - MYSQL_DATABASE=react_demo
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Set this to be within the available range (e.g., 0.5 for half a CPU)
        reservations:
          cpus: '0.25'  # Optional, reserve part of a CPU
    command: ./wait-for-it.sh --host=db --port=3306 -- npm run migrate-seed-start

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example@123
      MYSQL_DATABASE: react_demo
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
