name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
          git clone https://github.com/aashutoshtaikar/node-api-demo
          cd node-api-demo
          
          # Stop and remove any existing containers
          docker-compose -f docker-compose.yml down -v

          # Start the containers with the latest images
          docker-compose -f docker-compose.yml up --build

          docker-compose run app sh
        EOF
