name: Build and Deploy to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          sudo su
          
          git clone https://github.com/aashutoshtaikar/node-api-demo
          cd node-api-demo
          
          # Stop and remove any existing containers
          docker-compose -f docker-compose.yaml down -v

          # Start the containers with the latest images
          docker-compose -f docker-compose.yaml up --build

          docker-compose run app sh
        EOF
